"""registry tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-14 03:18:46.625580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registered_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registered_models_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_registered_models_owner_id'), ['owner_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_model_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('NONE', 'STAGING', 'PRODUCTION', 'ARCHIVED', name='model_stage'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registered_model_id'], ['registered_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registered_model_id', 'version', name='uq_model_versions_model_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_registered_model_id'), ['registered_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_stage'), ['stage'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_stage'))
        batch_op.drop_index(batch_op.f('ix_model_versions_registered_model_id'))

    op.drop_table('model_versions')
    with op.batch_alter_table('registered_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_models_owner_id'))
        batch_op.drop_index(batch_op.f('ix_registered_models_name'))

    op.drop_table('registered_models')
    # ### end Alembic commands ###
